### ISSUE TITLE
`strcpy` used instead of `strncpy`

### ISSUE THREAD

**Issue by kunaltyagi** [Mashpoe/cpp-string#1]

**Comment by Mashpoe** [comment]
since we already know the length before we use strcpy anyway, I think it should be changed to memcpy because strncpy isn't binary safe (i.e. memcpy will allow users to store data that contains null bytes if they chose to)

**Comment by Mashpoe** [comment]
alright, I just replaced all of the uses of strcpy with memcpy, and added SSO. Should be good now
